### ISSUE TITLE
Add Navigator 2.0 compatibility

### ISSUE THREAD

**Issue by emanuel-braz** [emanuel-braz/flutter_micro_app#19]
Lately I haven't had much free time, so to optimize my time and bring a more robust solution, we will take advantage of the GoRouter package to solve this issue.

https://pub.dev/packages/go_router

**Comment by msgtobala** [comment]
@emanuel-braz when can we expect this feature?

**Comment by emanuel-braz** [comment]
Hi @msgtobala, I'm working to create a plugin to make possible using GoRouter together with flutter_micro_app, and I'll probably finish that this week.

Context: This package is not intended to be a Routing solution, the main focus is Event Driven Development, so you can communicate different modules/project/feature/programming languages using only one pattern, and without strong coupling.

Although the routing system works, it is quite simple, and since there are already more robust solutions for this, I advise taking advantage of this, integrating with other routing libraries, like GoRouter.

**Comment by emanuel-braz** [comment]
I'm also adapting the Flutter DevTools MicroBoard in order to display GoRouter routes, so you can inspect and export them to a excel file.

![image](https://github.com/user-attachments/assets/8056cc8c-289f-4979-9848-84d3d335876e)
